<?php 
	$this->pageTitle = 'About Us';
	$this->headTitle($this->pageTitle);
?>

<div id="primary">
	<article>
        <h2>A fresh approach to creative challenges, business solutions and training</h2>
        <p>Whether it's a film for your website, a training video, a new house style for your company or a new painting for your reception area, we can help.</p>
        
        <p>We have expertise across a wide range of sectors in the creative industries which you can tap into for your individual needs.</p>
        
        <p>We provide short courses in the creative arts and bespoke training for individual companies.</p>
        
        <p>Our industry professionals, graduates and students generate a potent mix of expertise, talent and creativity.</p>
	</article>
</div>