<?php 
	$this->pageTitle = 'Privacy Policy';
	$this->headTitle($this->pageTitle);
?>

<div id="primary">
	<article>
		<p>At the University of Hertfordshire we believe strongly in protecting our users' privacy. We will not wilfully disclose information about our users to any third party without first receiving the relevant user's consent. This Privacy Policy sets out the privacy practices for the services offered on any University of Hertfordshire ('the University') owned and/or operated websites ('the Website'). Some parts of our on-line systems and services and our collaborative agreements are operated on our behalf by third-party organisations. By submitting your personal information you are consenting to the University holding it, in accordance with this policy, and where necessary carrying out these services by providing the relevant information to such organisations.</p>

		<p>This Privacy Policy may be updated from time-to-time. You should check this page regularly to ensure that you are happy with any changes.</p>

		<p><a href="http://sitem.herts.ac.uk/secreg/upr/pdf/IM10-Privacy%20Policy-v02%200.pdf">Download the University's online privacy policy</a></p>
    </article>
</div>