<?php
$this->headTitle('Creative Innovation & Training: Admin Panel');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <?php echo $this->headMeta() ?> 
  <?php echo $this->headTitle() ?> 
  <?php echo $this->headLink()->prependStylesheet('/css/iehacks.css', 'screen', 'IE')
			      ->prependStylesheet('/css/admin-styles.css')
  			      ->prependStylesheet('/css/reset.css') ?> 
  <?php echo $this->headScript()->prependFile('/js/jquery-1.6.2.min.js')
				->appendFile('/js/admin-core.js') ?>

</head>
<body class="<?php echo $this->bodyClass() ?>">

<!--
  <a href="<?php echo $this->url(array('module'=>'a','controller'=>'b','action'=>'c'), 'default', true) ?>">Guestbook</a>
-->

<div id="wrapper">

<header>
  <h1>Admin: <?php echo $this->escape($this->pageTitle) ?></h1>
  <nav>
    <?php echo $this->navigation()->menu(Zend_Registry::get('NavigationAdmin')) ?>
  </nav>
</header>

<!--
<div id="breadcrumbs">
  <?php echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->setSeparator(' / ')->render(Zend_Registry::get('NavigationAdmin')); ?>
</div>
-->

<div id="content">

<?php echo $this->layout()->content ?>

</div>

</div>

</body>
</html>
