<?php 
	$this->pageTitle = 'Animation & VFX';
	$this->headTitle($this->pageTitle);
?>

<div id="primary">
	<article>
		<p>Animation makes up a very large part of creative industries in the UK.  We have excellent students who are ready to produce the next generation of games, CGI and visual effects for TV and film, supervised by our staff who are industry leaders.  We can create 3D CAD models of objects including cars, boats, virtual environments and figures. If you are looking to produce an advert or a piece of viral marketing using animation, we can work with you to create the best look and content to get your message across.</p>
	</article>
</div>