<?php 
	$this->pageTitle = 'Fashion';
	$this->headTitle($this->pageTitle);
?>

<div id="primary">
	<article>
		<p>Our fashion expertise is centred around branding, design, fit and sizing. We have a great deal of experience in these areas and can offer strategic planning, grading and regrading services, pattern cutting and of course consultancy around branding and sizing issues. We can also provide bespoke training to fashion industry professionals in these areas.</p>
	</article>
</div>