<?php 
	$this->pageTitle = 'Filming';
	$this->headTitle($this->pageTitle);
?>

<div id="primary">
	<article>
		<p>We work with a range of public and private organisations to create films and DVDs, including promotional films, training videos, and documentaries. Our film crews are made up of third year students who are supervised and advised by our tutors and in house professionals, all of whom have a wealth of industry experience.</p>
		<p>Our High Definition film and TV studio can be used for filming, and set up exactly how you need it. We also have a range of location kits for filming at different sites. We edit and reproduce DVDs for you as well.</p>
	</article>
</div>