<?php 
	$this->pageTitle = 'Graphic Design';
	$this->headTitle($this->pageTitle);
?>

<div id="primary">
	<article>
		<p>We are the region's most innovative creative studio, offering a full range of design services, from corporate branding and advertising to interactive media design and photography. Based within the University of Hertfordshire, we have access to the freshest award winning new talent.  Whether it's a full corporate rebrand or a small promotional piece you're looking for, we are here to help</p>
	</article>
</div>