<?php 
	$this->pageTitle = 'Interior Architecture & Design';
	$this->headTitle($this->pageTitle);
?>

<div id="primary">
	<article>
		<p>Interior architecture and design with us goes far beyond choosing wall colours and finishes. We can design anything for the interior or exterior of a building, including everything from unique lighting fixtures to the redevelopment of a reception area, right through to the design of external features such as public pathways. We can design single, unique objects or rooms and areas. Supported by qualified architects, we relish the opportunity to meet the challenges that you have.</p>
	</article>
</div>