<?php 
	$this->pageTitle = 'Interactive Media';
	$this->headTitle($this->pageTitle);
?>

<div id="primary">
	<article>
		<p>Interactive media in the 21st century is a rapidly changing and growing market. We can help you develop new content and platforms, and potentially assist you in accessing funding for this if what you're doing is groundbreaking. We have experience in web and device based platforms, as well as in projects connected with the development and application of metadata.</p>
	</article>
</div>