<?php 
	$this->pageTitle = 'Model Making';
	$this->headTitle($this->pageTitle);
?>

<div id="primary">
	<article>
		<p>Life is better in 3D! Whether you'd like to have a replica film prop, a model house or shop, even a model ice cream van made, look no further. We have extensive experience in building a range of models, many of which have been used in exhibitions, for training purposes and of course in films.</p>
	</article>
</div>