<?php 
	$this->pageTitle = 'Music & Audio';
	$this->headTitle($this->pageTitle);
?>

<div id="primary">
	<article>
		<p>We engineer, record, mix and produce for a wide range of music and audio-visual events.  In our state-of-the-art studios or on location, we have the ability to capture all types of music – from studio band recording via contemporary electronic, to full-scale live orchestral and choral works. We also offer consultancy to artists, bands and organisations on marketing, promotion and the business of music.</p>
	</article>
</div>