<?php 
	$this->pageTitle = 'Photography';
	$this->headTitle($this->pageTitle);
?>

<div id="primary">
	<article>
		<p>We work closely with industry providing a wide range of commercial photography services. The team, led by experienced industry practitioners includes a group of young, highly creative and enthusiastic industry focussed graduates and students.</p>
		<p>With the latest equipment and post production technologies available in our studios and laboratories we can provide professional advice and undertake a wide range of photographic assignments to meet your requirements.</p>
		<p>Our team has worked with many national and international clients on creative assignments in corporate imagery, advertising, industrial/architectural photography and fashion shoots.</p>
	</article>
</div>