<?php 
	$this->pageTitle = 'Product Design';
	$this->headTitle($this->pageTitle);
?>

<div id="primary">
	<article>
		<p>Our team has worked with  entrepreneurs and inventors to help develop their innovative ideas, and help them to prepare  their pitch to manufacturers and developers, Our team has the knowledge, skills and experience advise on design and  usability and  to develop your idea into a CAD drawing, with the potential to create a prototype using our specialist equipment.</p>
	</article>
</div>