<?php 
	$this->pageTitle = 'Facilities Hire';
	$this->headTitle($this->pageTitle);
?>

<div id="primary" class="no_margin">
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/3dconst.jpg">
        <header>
            <h2>3D Workshop: Construction &amp; Carving</h2>
        </header>
        <div class="article_content"><strong>The woodworking machine area</strong> has circular and band saws to cut and shape, a sander for finishing, a pedestal drill and benches for fabrication and a mitre guillotine for stretcher and frame making.</div>
    </article>
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/3dform.jpg">
        <header>
            <h2>3D Workshop: Forming &amp; Finishing</h2>
        </header>
        <div class="article_content">For <strong>metal working</strong>, there is a forge and anvil allowing blacksmithing techniques and rolling bars allow for the shaping and forming of sheet. The <strong>welding bay</strong> gives access to heavy and light welding equipment including MIG welding for steel and oxyacetylene for cutting, welding and braising, with propane for soldering. There is also a <strong>sculpting and moulding</strong> facility where figures for special effects and fine art can be built and moulded. Also, we have a new fully ventilated <strong>fibreglass workshop</strong> for creating moulds and castes in fibreglass.</div>
    </article>
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/av.png">
        <header>
            <h2>A/V Stores</h2>
        </header>
        <div class="article_content">AV stores in the School house an increasing stock of bookable film and TV equipment.</div>
    </article>
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/cddvd.jpg">
        <header>
            <h2>CD/DVD Copying</h2>
        </header>
        <div class="article_content">We are able to copy CDs and DVDs for you. Please enquire about prices.</div>
    </article>
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/dubbingsuite.jpg">
        <header>
            <h2>Dubbing Suites</h2>
        </header>
        <div class="article_content">A series of sound dubbing and monitoring suites which incorporate mixing desks, video and audio playback (surround sound) as well as foley materials, microphones, players and peripherals.</div>
    </article>
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/fashion.jpg">
        <header>
            <h2>Fashion Workshops</h2>
        </header>
        <div class="article_content">We have a variety of facilities including a cutting space with pattern cutting tables, sewing machines, overlockers and tailors' mannequins. These facilities are complemented by industrial steam presses and an edge fuser with a cutting table. The computer suite runs the Adobe Creative suite and the Gerber software set.</div>
    </article>
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/filmtv_postproduction.jpg">
        <header>
            <h2>Film &amp; TV Postproduction</h2>
        </header>
        <div class="article_content">This suite provides Apple computers connected to dual screens with video input and output devices and runs integrated Final Cut Pro which includes editing picture and sound as well as DVD authoring and production.</div>
    </article>
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/filtv_studio.jpg">
        <header>
            <h2>Film &amp; TV Studio</h2>
        </header>
        <div class="article_content">A four camera space with a composite studio floor and full lighting rig enclosed by  drapes and a green screen. The studio has a control suite with vision, sound and lighting mixers and a small green room. There is a range of microphones, booms, dollies, tracks, cranes and steadycams. 
									<br /><br />The fixed facilities are supplemented by location equipment that can be hired and includes HDV cameras, location monitors, disc recorders, microphone tripods and lighting kits.</div>
    </article>
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/ceramics.jpg">
        <header>
            <h2>Glass, metal, ceramics</h2>
        </header>
        <div class="article_content">The <strong>glass workshop</strong> has equipment for cutting and working glass using abrasives and water cooled drills, these are supplemented by a flame work area. There are kilns for fusing and forming glass. The <strong>small metals and jewellery</strong> facility has hand and machine tools including a fly press for working non ferrous metals, for example soldering, pressing and forming for jewellery and fine work. Hand built and thrown work can be created in the <strong>ceramics workshop</strong> with a variety of slip glazes and clay materials. The workshop has a damp room, a glaze area and a kiln room with a variety of different kilns. </div>
    </article>
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/darkrooms.jpg">
        <header>
            <h2>Photographic Workshops</h2>
        </header>
        <div class="article_content">We offer dark rooms for developing black and white film and a processor for colour work.  We also have a finishing area for glazing, toning and drying prints.</div>
    </article>
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/photostudio.jpg">
        <header>
            <h2>Photography Studio</h2>
        </header>
        <div class="article_content">Two photography studios are available for hire, both of which house lighting rigs and drapes as well as backgrounds that can be used to create a variety of different backdrops to suit your needs are available for hire. The studios are ideal for the shooting of still and video materials. Technical support can be provided at extra cost.</div>
    </article>
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/digitalprint.png">
        <header>
            <h2>Print Shop</h2>
        </header>
        <div class="article_content">The University print shop runs four A2 inkjet printers and one large-scale press machine which create high quality print output for photography and graphics.</div>
    </article>
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/printmaking.jpg">
        <header>
            <h2>Printmaking</h2>
        </header>
        <div class="article_content">The area supports a range of printing practices with a number of print tables configured for screen printing. It has plate and stone litho presses. Two large Victorian presses are for lino and the etching facility includes ink-mixing, an aquatint box, hot plates and a series of presses for different sized prints.</div>
    </article>
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/rp.jpg">
        <header>
            <h2>Rapid-prototyping</h2>
        </header>
        <div class="article_content">This unit has a range of equipment linked to computers for digitally controlled output. Solid and freeform models can be produced as well as accurate 3D models of existing forms which can be modified, manipulated and rendered before they are output as an animation or a 3D print. A range of materials can also be cut and engraved.</div>
    </article>
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/recording.jpg">
        <header>
            <h2>Recording Studios</h2>
        </header>
        <div class="article_content">Studio 1 is a 24 track recording facility with a control room housing a 'solid state logic' mixing console and 4.1 surround sound monitoring system. Studio 2 is a 32 channel, digital Yamaha O2R desk with control and live room for ensembles of 3 to 4 players. We always provide engineer support. Two music suites are also available for hire, with Macintosh computers facilitating digital mixing, recording, sampling and composing. There is also a range of software programmes available to use, plus industry standard applications.</div>
    </article>
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/textile.jpg">
        <header>
            <h2>Textiles</h2>
        </header>
        <div class="article_content">We also have a specialist area for textiles construction, including a dye lab, a baking oven for curing dyed items and felt making facilities. It also includes A3 sized heat transfer printing, a facility for stretching screens and exposing photographic emulsions.</div>
    </article>
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/2dimaging.jpg">
        <header>
            <h2>The 2D Imaging Suite</h2>
        </header>
        <div class="article_content">Two suites of Macs with large scale monitors linked to A4 and A3 scanners with A4 B&amp;W and A3 Colour Lasers for proofing prints. They primarily run the Adobe Creative suite that includes In Design, Illustrator and Photoshop that are focused on the manipulation of text and image as well as Acrobat and GoLive for file transfer and web.  A few machines also run Quark Xpress for print preparation. </div>
    </article>
    
    <article class="article_box_alt">
        <img width="200" height="200" src="/images/pc.jpg">
        <header>
            <h2>The 3D Suite</h2>
        </header>
        <div class="article_content">This facility runs fifty 8 core i7 PC's with a standard package of software such as Adobe Master suite CS4. It also supports specialist digital 3D Design & Modelling activities which use programmes such as Solid Works and Rhino for 3D modelling, and a spatial design package called Vector Works.</div>
    </article>

</div>