<?php 
$this->pageTitle = 'Course List';
$this->headTitle($this->pageTitle);
?>

<table cellpadding="0" cellspacing="0" border="0" class="display" id="courses">

	<thead>
		<tr>
			<th>ID</th>
			<th>Title</th>
			<th>Category</th>
		</tr>
	</thead>

	<tbody>

	<?php foreach ($this->courses as $course): ?>
		<tr url="somelink">
			<td><?php echo $this->escape($course->Id) ?></td>
			<td><?php echo $this->escape($course->Title) ?></td>
                        <td><?php echo $this->escape($course->CategoryID) ?></td>
		</tr>
	<?php endforeach ?>

	</tbody>

</table>
