<?php
$this->pageTitle = 'Course - ' . $this->course->Title;
$this->headTitle($this->course->Title);
?>

<nav>
<ul class="course_options">
	<li><a href="<?php echo $this->url(array('module' => 'admin','controller'=>'course','action'=>'edit','id'=>$this->course->Id), null, TRUE) ?>">Edit Course</a></li>
	<li><a class="last" href="<?php echo $this->url(array('module' => 'admin','controller'=>'course','action'=>'delete','id'=>$this->course->Id), null, TRUE) ?>">Delete Course</a></li>
</ul>
</nav>

<table class="standardtable">
	<thead>
		<tr>
			<th>Field</th>
			<th>Value</th>
		</tr>
	</thead>
	<tbody>
		<tr>
                        <td>Title</td>
                        <td><?php echo $this->escape($this->course->Title) ?></td>
                </tr>
		<tr>
			<td>ID</td>
			<td><?php echo $this->course->Id ?></td>
		</tr>
                <tr>
                        <td>URL Key</td>
                        <td><?php echo $this->course->URLKey ?></td>
                </tr>
		<tr>
			<td>Category</td>
			<td><?php echo $this->escape($this->course->CategoryName) ?></td>
		</tr>
		<tr>
			<td>Subtitle</td>
			<td><?php echo $this->escape($this->course->Subtitle) ?></td>
		</tr>
		<tr>
			<td>Course Image (not to size)</td>
			<td><?php echo $this->Image('Course Image', '/uploads/'. $this->course->Image, array('alt' => 'Course Image'), '150x150') ?></td>
		</tr>
		<tr>
			<td>Aims of the course</td>
			<td><?php echo $this->paragraphText($this->course->Aims) ?></td>
		</tr>
		<tr>
			<td>Who is it for?</td>
			<td><?php echo $this->paragraphText($this->course->TargetAudience) ?></td>
		</tr>
		<tr>
			<td>What does the course cover?</td>
			<td><?php echo $this->paragraphText($this->course->Brief) ?></td>
		</tr>
		<tr>
			<td>Booking URL</td>
			<td><a href="<?php echo $this->escape($this->course->BookingURL) ?>"><?php echo $this->escape($this->course->BookingURL) ?></a></td>
		</tr>
		<tr>
			<td>Related Courses:</td>
			<td><?php foreach($this->relatedcourses as $relatedcourse) echo $relatedcourse->RelatedCourseTitle . '<br />'; ?></td>
		</tr>
		<tr>
			<td>Meta Keywords</td>
			<td><?php echo $this->escape($this->course->MetaKeywords) ?></td>
		</tr>
		<tr>
			<td>Meta Description</td>
			<td><?php echo $this->escape($this->course->MetaDescription) ?></td>
		</tr>
	</tbody>
</table>

<a href="<?php echo $this->url(array('module' => 'admin','controller'=>'study-option','action'=>'add','id'=>$this->course->Id), null, TRUE) ?>"><img src="/images/addstudyoption.png" alt="Add Study Option" /></a>

<table class="standardtable">
        <thead>
                <tr>
                        <th>Semester</th>
                        <th>Days</th>
			<th>Dates</th>
			<th>Times</th>
			<th>Duration</th>
			<th>Fee</th>
			<th>Course Code</th>
			<th>Location</th>
			<th></th>
                </tr>
        </thead>
        <tbody>
		<?php foreach($this->studyoptions as $studyoption): ?>
		<tr>
			<td><?php echo $studyoption->Semester ?></td>
			<td><?php echo $studyoption->Days ?></td>
			<td><?php echo $studyoption->Dates ?></td>
			<td><?php echo $studyoption->Times ?></td>
			<td><?php echo $studyoption->Duration ?></td>
			<td><?php echo $studyoption->Fee ?></td>
			<td><?php echo $studyoption->Code ?></td>
			<td><?php echo $studyoption->Location ?></td>
			<td>
            	<a href="<?php echo $this->url(array('module' => 'admin','controller'=>'study-option','action'=>'delete','studyoptionid'=>$studyoption->Id), null, TRUE) ?>" class="deletebutton">Delete</a>
                <a href="<?php echo $this->url(array('module' => 'admin','controller'=>'study-option','action'=>'edit','id'=>$studyoption->Id,'courseid'=>$this->course->Id), null, TRUE) ?>" class="editbutton">Edit</a>
            </td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
