<?php 
	$this->pageTitle = 'Bespoke Services';
	$this->headTitle($this->pageTitle);
?>

<div id="primary">
	<article>
        <p>In today's economic environment it is essential that all businesses address the constant need for change. Learning new skills is not only beneficial to individuals but also for corporations who want to make sure that they address the need for advancing their employees' professional skills, are up to date with current business practice, and have the knowledge to be more effective in the business place. The University of Hertfordshire is able to deploy specialist teams who, as leaders in their own fields, offer clients that have complex and innovative creative projects the best available means to move forward.</p>
    
        <p>Key members of our academic and professional teams work as consultants in areas that include music, media, art and design. Our expertise have fostered and helped the growth and success of businesses and projects, from their conception and early stages of their development, through to implementation and subsequent evaluation. Our work is based on a belief that comprehensive, well-planned training lays the foundations for future success. Our bespoke consultancy and training offer is tailored to meet your specific needs.</p>
        
        <p>Services we offer include:<br />
        – Specific one day courses either on site in the School of Creative Arts or at your business<br />
        – Specially designed programmes to meet your business priorities<br />
        – Workshops for your team<br />
        – In-depth research and evaluation</p>
        
        <p>Our experience has shown how beneficial it can be for independent, academic experts to come to businesses and projects as listeners, catalysts and analysts, without pre-conceived ideas or any wish to impose particular notions on subsequent business activity.</p>
	</article>
</div>