<?php 
	$this->pageTitle = 'Art Services';
	$this->headTitle($this->pageTitle);
?>

<div id="primary">
	<article>
		<p>We have an art consultant on our team who has a wealth of experience working with private clients, businesses and commercial teams to provide art and design to suit their needs. Whether you want a specially commissioned piece of artwork for your home, or a series of works for your business, we have the expertise to guide you. We also consult and project manage large-scale works such as public art sculptures, themed community projects or interactive pieces for new buildings.</p>

		<p>Our huge network of artists is at your disposal to help you find exactly the right artwork, whatever your requirements are. So why not make use of our creative knowledge and expertise? We have an excellent record of working with individuals and industry partners from a wide range of sectors.</p>

		<p>For further information please contact Tricia Bryan at <a href="mailto:p.bryan@herts.ac.uk">p.bryan@herts.ac.uk</a></p>
    </article>
</div>