<p>Are you sure that you want to delete <strong><?php echo $this->escape($this->article->Title) ?></strong>?</p>

<form action="<?php echo $this->url(array('module'=>'admin', 'controller'=>'news', 'action'=>'delete')); ?>" method="post">
<div>
<input type="hidden" name="id" value="<?php echo $this->article->Id; ?>" />
<input type="submit" name="del" value="Yes" />
<input type="submit" name="del" value="No" />
</div>
</form>